name: Daily E2E Tests

on:
  schedule:
    # 毎日午前 9:00 (JST) に実行 (UTC 0:00)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 手動実行も可能

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Build application
        run: npm run build
        env:
          CI: true

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Create output directories
        run: |
          mkdir -p playwright-report
          mkdir -p output

      - name: Start application server
        run: npm start &

      - name: Wait for server to be ready
        run: |
          sleep 5
          curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000 || exit 1

      - name: Run E2E tests with Playwright
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Run E2E tests with CodeceptJS
        run: npm run test:codecept
        env:
          CI: true

      - name: Upload CodeceptJS test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codeceptjs-output
          path: output/
          retention-days: 30

  notification:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Notify test results
        run: |
          if [ "${{ needs.e2e-tests.result }}" == "success" ]; then
            echo "✅ E2E tests passed successfully"
          else
            echo "❌ E2E tests failed"
            exit 1
          fi
